# Generated by Django 4.2 on 2023-07-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_images', '0002_alter_image_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='total_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-total_likes'], name='app_images__total_l_979039_idx'),
        ),
    ]
