# Generated by Django 4.2 on 2023-05-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='users/default.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
