# Generated by Django 4.2 on 2023-05-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_contact_contact_account_con_created_8bdae6_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='users/default.png', null=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
